#!/usr/bin/env bash

#                                               _   
#                                              | |  
#      ___ _ __ ___  _   _ ___ ______ __ _ _ __| |_ 
#     / __| '_ ` _ \| | | / __|______/ _` | '__| __|
#    | (__| | | | | | |_| \__ \     | (_| | |  | |_ 
#     \___|_| |_| |_|\__,_|___/      \__,_|_|   \__|
#                                                   
#  Name: cmus-art
#  Time: Wed Jan 12 03:08:20 PM IST 2022
#  Author: Kushagra


-------------------------------------------------------------------------------
-------------------------------------------------------------------------------


                                                   
#  _      _ _        _ _     
# (_)_ _ (_) |_   __| (_)_ _ 
# | | ' \| |  _| / _` | | '_|
# |_|_||_|_|\__| \__,_|_|_| 	(checking if the temp dir already exists, if not creating it)
#                            

if [[ -d /tmp/art ]]; then
     rm -r /tmp/art/
     mkdir /tmp/art/
else
     mkdir /tmp/art/
fi



-------------------------------------------------------------------------------


                                  
#  _ _ _  _ _ _    __ __ ___ ____ _ 
# | '_| || | ' \  / _/ _` \ V / _` |
# |_|  \_,_|_||_| \__\__,_|\_/\__,_|  (checking which terminal you use and running cava in it)
#

term=$(echo $TERM | cut -d '-' -f 1)
$term -e cava &



-------------------------------------------------------------------------------



#   __     _      _               _   
#  / _|___| |_ __| |_    __ _ _ _| |_ 
# |  _/ -_)  _/ _| ' \  / _` | '_|  _|  (used ffmpeg to fetch art and feh to display)
# |_| \___|\__\__|_||_| \__,_|_|  \__|	(updates every 2s)
#

fileCurrent="$(cmus-remote -Q | grep "file" | sed "s/file //")"
ffmpeg -y -i "$fileCurrent" /tmp/art/art.jpeg &> /dev/null 
feh -g 250x250+1670+830 -x --scale-down --image-bg black /tmp/art/art.jpeg &

while [[ true ]]; do
	fileOLD="$(cmus-remote -Q | grep "file" | sed "s/file //")"
	sleep 2
	fileNOW="$(cmus-remote -Q | grep "file" | sed "s/file //")"

	if [[ "$fileNOW" != "$fileOLD" ]]; then
		ffmpeg -y -i "$fileNOW" /tmp/art/art.jpeg &> /dev/null
	fi
done


-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
